const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=s=>{s=Math.max(0,Math.floor(s||0));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`};
let stream=null,worker=null,recorder=null,recordingTimer=null,frameTimer=null,clockTimer=null;
let calibration=[],calibrating=false,gameActive=false,sessionId=null,startPerf=0,finalDuration=0;
let rules=null,events=[],undoStack=[],pendingShot=null,lastVisionState=null,lastConfidence=0;
let videoChunkIndex=0,videoChunkStart=0,objectUrls=[],safetyArmed=false;

const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open("poolcam-v3",1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("sessions"))d.createObjectStore("sessions",{keyPath:"id"});if(!d.objectStoreNames.contains("videos"))d.createObjectStore("videos",{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function dbPut(store,v){const d=await dbp;return new Promise((res,rej)=>{const t=d.transaction(store,"readwrite");t.objectStore(store).put(v);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function dbAll(store){const d=await dbp;return new Promise((res,rej)=>{const t=d.transaction(store);const r=t.objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbClear(store){const d=await dbp;return new Promise((res,rej)=>{const t=d.transaction(store,"readwrite");t.objectStore(store).clear();t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function nowSec(){return gameActive?(performance.now()-startPerf)/1000:finalDuration}
function name(i){return i===0?($("p1").value.trim()||"Player 1"):($("p2").value.trim()||"Player 2")}
function setEngine(text,live=false){$("engineBadge").textContent=text;$("engineBadge").className="badge "+(live?"live":"idle")}
function syncSetup(){$("p1Top").textContent=name(0);$("p2Top").textContent=name(1);$("breaker").options[0].textContent=name(0);$("breaker").options[1].textContent=name(1);$("rulesLabel").textContent=$("ruleset").value==="wpa"?"WPA 8-ball":"House rules";$("houseSettings").classList.toggle("hidden",$("ruleset").value!=="house")}
["p1","p2"].forEach(id=>$(id).addEventListener("input",syncSetup));$("ruleset").onchange=syncSetup;syncSetup();

document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.page+"Page").classList.add("active");renderAll()});
$("settingsBtn").onclick=()=>$("settingsSheet").classList.remove("hidden");$("closeSettingsBtn").onclick=()=>$("settingsSheet").classList.add("hidden");

async function startCamera(){
  const constraints={video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30,max:30}},audio:true};
  try{stream=await navigator.mediaDevices.getUserMedia(constraints)}catch(e){try{stream=await navigator.mediaDevices.getUserMedia({...constraints,audio:false})}catch(err){alert("Camera could not start: "+err.message);return}}
  $("video").srcObject=stream;$("cameraEmpty").classList.add("hidden");$("cameraBtn").disabled=true;$("calibrateBtn").disabled=false;setupWorker();setTimeout(resizeOverlay,500);setEngine("Camera ready",true);
  const saved=localStorage.getItem("poolcam-v3-cal");if(saved){try{calibration=JSON.parse(saved)}catch{calibration=[]}}
  if(calibration.length===4){$("startBtn").disabled=false;$("engCal").textContent="Calibrated";$("calibrateBtn").textContent="Recalibrate";configureWorker();drawOverlay()}updateStorage();
}
$("cameraBtn").onclick=startCamera;window.addEventListener("resize",resizeOverlay);
function videoRect(){const stage=$("videoStage").getBoundingClientRect(),v=$("video"),vw=v.videoWidth||16,vh=v.videoHeight||9,stageAR=stage.width/stage.height,videoAR=vw/vh;let w,h,left,top;if(videoAR>stageAR){w=stage.width;h=w/videoAR;left=0;top=(stage.height-h)/2}else{h=stage.height;w=h*videoAR;top=0;left=(stage.width-w)/2}return{stage,w,h,left,top}}
function resizeOverlay(){const c=$("overlay"),r=$("videoStage").getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.style.width=r.width+"px";c.style.height=r.height+"px";drawOverlay()}
function drawOverlay(){const c=$("overlay"),ctx=c.getContext("2d"),d=devicePixelRatio||1;ctx.clearRect(0,0,c.width,c.height);if(!calibration.length)return;const vr=videoRect(),map=p=>({x:(vr.left+p.x*vr.w)*d,y:(vr.top+p.y*vr.h)*d});ctx.lineWidth=3*d;ctx.strokeStyle="#55e68c";ctx.fillStyle="#55e68c";ctx.beginPath();calibration.forEach((p,i)=>{const q=map(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});if(calibration.length===4)ctx.closePath();ctx.stroke();calibration.forEach((p,i)=>{const q=map(p);ctx.beginPath();ctx.arc(q.x,q.y,7*d,0,Math.PI*2);ctx.fill();ctx.font=`${13*d}px sans-serif`;ctx.fillText(String(i+1),q.x+10*d,q.y-8*d)})}
const calNames=["top-left","top-right","bottom-right","bottom-left"];
$("calibrateBtn").onclick=()=>{calibration=[];calibrating=true;document.body.classList.add("calibrating");$("calibrationGuide").classList.remove("hidden");$("calText").textContent="Tap "+calNames[0]+" corner";drawOverlay()};
$("cancelCalBtn").onclick=()=>finishCalibration(false);
$("overlay").addEventListener("pointerdown",e=>{if(!calibrating)return;e.preventDefault();const stage=$("videoStage").getBoundingClientRect(),vr=videoRect(),sx=e.clientX-stage.left,sy=e.clientY-stage.top;if(sx<vr.left||sx>vr.left+vr.w||sy<vr.top||sy>vr.top+vr.h)return;calibration.push({x:(sx-vr.left)/vr.w,y:(sy-vr.top)/vr.h});drawOverlay();if(calibration.length===4)finishCalibration(true);else $("calText").textContent="Tap "+calNames[calibration.length]+" corner"},{passive:false});
function finishCalibration(ok){calibrating=false;document.body.classList.remove("calibrating");$("calibrationGuide").classList.add("hidden");if(ok&&calibration.length===4){localStorage.setItem("poolcam-v3-cal",JSON.stringify(calibration));$("startBtn").disabled=false;$("engCal").textContent="Calibrated";$("calibrateBtn").textContent="Recalibrate";configureWorker();drawOverlay()}else{const saved=localStorage.getItem("poolcam-v3-cal");calibration=saved?JSON.parse(saved):[];drawOverlay()}}
function pocketZones(){if(calibration.length!==4)return[];const[a,b,c,d]=calibration,mid=(p,q)=>({x:(p.x+q.x)/2,y:(p.y+q.y)/2}),len=(p,q)=>Math.hypot(q.x-p.x,q.y-p.y),sides=[{p:a,q:b},{p:b,q:c},{p:c,q:d},{p:d,q:a}].sort((x,y)=>len(y.p,y.q)-len(x.p,x.q)),mids=[mid(sides[0].p,sides[0].q),mid(sides[1].p,sides[1].q)];return[a,b,c,d,...mids].map(p=>({...p,r:.055}))}
function setupWorker(){if(worker)worker.terminate();worker=new Worker("./worker.js");worker.onmessage=e=>{const m=e.data;if(m.type==="motion"){$("tableStateBadge").textContent="Table: "+(m.moving?"MOVING":"STILL");$("engMotion").textContent=(m.ratio*100).toFixed(1)+"%"}else if(m.type==="stableState"){lastVisionState=m.state;$("ballCountBadge").textContent="Balls: "+m.state.count;$("engBalls").textContent=String(m.state.count);$("engCue").textContent=m.state.cue?"Seen":"Not seen";$("engPocket").textContent=(m.pocket*100).toFixed(2)+"%"}else if(m.type==="shotComplete")onShotComplete(m)};configureWorker()}
function configureWorker(){if(worker)worker.postMessage({type:"config",sensitivity:+$("sensitivity").value,table:calibration.length===4?calibration:null,pockets:pocketZones()})}$("sensitivity").oninput=configureWorker;
function startFrames(){const v=$("video"),c=$("analysisCanvas"),ctx=c.getContext("2d",{willReadFrequently:true});clearInterval(frameTimer);frameTimer=setInterval(()=>{if(!gameActive||v.readyState<2||!worker)return;ctx.drawImage(v,0,0,c.width,c.height);const img=ctx.getImageData(0,0,c.width,c.height),rgba=new Uint8ClampedArray(img.data),gray=new Uint8Array(c.width*c.height);for(let i=0,j=0;i<rgba.length;i+=4,j++)gray[j]=(rgba[i]*3+rgba[i+1]*6+rgba[i+2])/10;worker.postMessage({type:"frame",rgba,gray,w:c.width,h:c.height,t:nowSec()},[rgba.buffer,gray.buffer])},300)}

function createRules(){rules=new PoolRules.EightBallRules({p1:name(0),p2:name(1),breaker:+$("breaker").value,raceTo:+$("raceTo").value,ruleset:$("ruleset").value,eightOnBreakWin:$("houseEightBreakWin").checked,scratchKitchen:$("houseScratchKitchen").checked})}
function startGame(){if(!stream||calibration.length!==4)return;createRules();events=[];undoStack=[];pendingShot=null;finalDuration=0;gameActive=true;sessionId="game-"+Date.now();startPerf=performance.now();videoChunkIndex=0;videoChunkStart=0;safetyArmed=false;$("startBtn").disabled=true;$("endBtn").disabled=false;$("switchPlayerBtn").disabled=false;setEngine("GAME LIVE",true);$("pendingReview").classList.add("hidden");worker?.postMessage({type:"reset"});startFrames();startRecordingLoop();clearInterval(clockTimer);clockTimer=setInterval(()=>{$("gameClock").textContent=fmt(nowSec())},500);addEvent("game-start",`${name(rules.current)} breaks`);saveSession(false);renderAll()}
$("startBtn").onclick=startGame;
async function endGame(){if(!gameActive)return;finalDuration=(performance.now()-startPerf)/1000;gameActive=false;clearInterval(frameTimer);clearInterval(clockTimer);await stopRecorder();$("endBtn").disabled=true;$("startBtn").disabled=false;$("switchPlayerBtn").disabled=true;setEngine("Saved",false);addEvent("game-end","Game ended");await saveSession(true);renderAll()}$("endBtn").onclick=endGame;

function bestMime(){for(const t of["video/mp4;codecs=h264,aac","video/mp4","video/webm;codecs=h264,opus","video/webm"])if(window.MediaRecorder&&MediaRecorder.isTypeSupported(t))return t;return""}
async function startOneRecorder(){if(!gameActive||!stream)return;const mime=bestMime(),bps=+$("videoQuality").value;let chunks=[];try{recorder=mime?new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:bps}):new MediaRecorder(stream)}catch{recorder=new MediaRecorder(stream)}recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onstop=async()=>{if(!chunks.length)return;const blob=new Blob(chunks,{type:chunks[0]?.type||mime||"video/mp4"}),end=nowSec();await dbPut("videos",{id:`${sessionId}-v${videoChunkIndex}`,sessionId,index:videoChunkIndex,start:videoChunkStart,end,createdAt:new Date().toISOString(),type:blob.type,blob});videoChunkStart=end;videoChunkIndex++;updateStorage();renderRecordings()};recorder.start();clearTimeout(recordingTimer);recordingTimer=setTimeout(()=>{if(recorder&&recorder.state!=="inactive"){recorder.stop();setTimeout(()=>{if(gameActive)startOneRecorder()},300)}},90000)}
function startRecordingLoop(){startOneRecorder()}function stopRecorder(){clearTimeout(recordingTimer);return new Promise(res=>{if(recorder&&recorder.state!=="inactive"){recorder.addEventListener("stop",()=>res(),{once:true});recorder.stop()}else res()})}

function onShotComplete(m){if(!gameActive||pendingShot)return;lastConfidence=m.confidence;$("engConfidence").textContent=Math.round(m.confidence*100)+"%";$("stateConfidence").textContent=`Shot confidence ${Math.round(m.confidence*100)}%`;const potted=Math.max(0,m.objectDelta??m.delta??0),scratch=!!m.cueGone;let result=scratch?"scratch":potted>0?"pot":"miss",conf=m.confidence;if(result==="pot"&&m.peakPocket<.00025)conf-=.12;if(result==="scratch"&&m.peakPocket<.00015)conf-=.08;conf=Math.max(0,Math.min(.99,conf));const shot={vision:true,t:m.t,result,pottedCount:potted,confidence:conf,peakPocket:m.peakPocket,before:m.before,after:m.after};if(safetyArmed){shot.result="safety";shot.pottedCount=potted;conf=.99;safetyArmed=false}shot.confidence=conf;if(conf>=+$("autoConfidence").value)applyShot(shot,"auto");else{pendingShot=shot;showReview(shot)}}
function showReview(s){$("pendingReview").classList.remove("hidden");const label=s.result==="scratch"?"Possible scratch":s.result==="pot"?`Possible pot (${s.pottedCount||1})`:"Possible miss";$("reviewText").textContent=label;$("reviewMeta").textContent=`Confidence ${Math.round(s.confidence*100)}% · please confirm`}
document.querySelectorAll("[data-review]").forEach(b=>b.onclick=()=>{if(!pendingShot)return;const r=b.dataset.review;if(r==="foul"){$("foulSheet").classList.remove("hidden");return}pendingShot.result=r;if(r==="pot"&&!pendingShot.pottedCount)pendingShot.pottedCount=1;if(r!=="pot")pendingShot.pottedCount=0;const s=pendingShot;pendingShot=null;$("pendingReview").classList.add("hidden");applyShot(s,"reviewed")});
function snapshotForUndo(){return{rules:rules?.snapshot(),events:JSON.parse(JSON.stringify(events)),pendingShot:pendingShot?JSON.parse(JSON.stringify(pendingShot)):null,safetyArmed}}
function pushUndo(){if(rules)undoStack.push(snapshotForUndo());if(undoStack.length>30)undoStack.shift()}
function applyShot(shot,source="manual"){
  if(!rules||!gameActive)return;pushUndo();
  if(source==="manual"&&pendingShot){shot={...pendingShot,...shot,t:pendingShot.t};pendingShot=null;$("pendingReview").classList.add("hidden")}
  const shooter=rules.current,result=rules.applyShot(shot),note=[];
  if(shot.result==="pot")note.push(`${shot.pottedCount||1} potted`);else if(shot.result==="scratch")note.push("Scratch");else if(shot.result==="safety")note.push("Safety");else if(shot.result==="foul")note.push("Foul");else note.push("No pot");
  if(shot.foulType)note.push(shot.foulType.replaceAll("-"," "));if(shot.confidence)note.push(`${Math.round(shot.confidence*100)}% confidence`);
  addEvent("shot",note.join(" · "),{player:shooter,shot:JSON.parse(JSON.stringify(shot)),ruleEvents:result.events});
  for(const ev of result.events||[]){if(ev.type==="rack-win"||ev.type==="rack-loss")addEvent("rack",`${name(ev.winner)} wins rack · ${ev.reason}`);if(ev.type==="eight-break-choice")addEvent("review",ev.message)}
  saveSession(false);renderAll();
}
document.querySelectorAll("[data-result]").forEach(b=>b.onclick=()=>{if(!gameActive)return;const r=b.dataset.result;applyShot({result:r,pottedCount:r==="pot"?1:0},"manual")});
$("switchPlayerBtn").onclick=()=>{if(!rules||!gameActive)return;pushUndo();const from=rules.current;rules.switchTurn();addEvent("turn",`Manual switch: ${name(from)} → ${name(rules.current)}`);saveSession(false);renderAll()};
$("safetyBtn").onclick=()=>{if(!gameActive||!rules)return;safetyArmed=!safetyArmed;rules.setSafety(safetyArmed);$("safetyBtn").textContent=safetyArmed?"◇ Safety armed":"◇ Declare Safety";addEvent("note",safetyArmed?`${name(rules.current)} declared safety`:"Safety cancelled");renderAll()};
$("highlightBtn").onclick=()=>{if(gameActive)addEvent("highlight","★ Highlight marked",{player:rules.current})};
$("undoBtn").onclick=()=>{const u=undoStack.pop();if(!u||!rules)return;rules.restore(u.rules);events=u.events;pendingShot=u.pendingShot;safetyArmed=u.safetyArmed;$("pendingReview").classList.toggle("hidden",!pendingShot);renderAll();saveSession(false)};
$("foulBtn").onclick=()=>$("foulSheet").classList.remove("hidden");$("closeFoulBtn").onclick=()=>$("foulSheet").classList.add("hidden");document.querySelectorAll("[data-foul]").forEach(b=>b.onclick=()=>{if(!gameActive)return;const ft=b.dataset.foul;$("foulSheet").classList.add("hidden");if(pendingShot){const s={...pendingShot,result:ft==="scratch"?"scratch":"foul",foulType:ft};pendingShot=null;$("pendingReview").classList.add("hidden");applyShot(s,"reviewed")}else applyShot({result:ft==="scratch"?"scratch":"foul",foulType:ft},"manual")});
$("eightBtn").onclick=()=>$("eightSheet").classList.remove("hidden");$("closeEightBtn").onclick=()=>$("eightSheet").classList.add("hidden");document.querySelectorAll("[data-eight]").forEach(b=>b.onclick=()=>{if(!gameActive)return;$("eightSheet").classList.add("hidden");applyShot({result:"pot",pottedCount:1,eight:b.dataset.eight,forceLegalEight:b.dataset.eight==="legal"},"manual")});
$("assignP1Solid").onclick=()=>{if(!rules)return;rules.assignGroups(0,"solid");addEvent("state",`${name(0)} = solids · ${name(1)} = stripes`);renderAll();saveSession(false)};$("assignP1Stripe").onclick=()=>{if(!rules)return;rules.assignGroups(0,"stripe");addEvent("state",`${name(0)} = stripes · ${name(1)} = solids`);renderAll();saveSession(false)};$("clearGroups").onclick=()=>{if(!rules)return;rules.clearGroups();addEvent("state","Groups reset: open table");renderAll();saveSession(false)};
$("p1RackWin").onclick=()=>manualRackWin(0);$("p2RackWin").onclick=()=>manualRackWin(1);function manualRackWin(i){if(!rules||!gameActive||rules.rackOver)return;pushUndo();rules.winRack(i,"manual rack result");addEvent("rack",`${name(i)} wins rack`);renderAll();saveSession(false)}
$("newRackBtn").onclick=()=>{if(!rules||!gameActive)return;if(rules.matchOver){alert("Match is already over. End this game and start a new match.");return}pushUndo();const nextBreaker=1-rules.breaker;rules.startRack(nextBreaker);addEvent("rack-start",`${name(nextBreaker)} breaks new rack`);worker?.postMessage({type:"reset"});renderAll();saveSession(false)};
function addEvent(type,note,extra={}){events.push({id:Date.now()+Math.random(),t:nowSec(),type,note,...extra})}
function renderRules(){if(!rules){$("currentPlayerBig").textContent="—";$("turnDetail").textContent="Start a game";return}$("currentPlayerBig").textContent=name(rules.current);$("turnDetail").textContent=rules.rackOver?`Rack over${rules.matchOver?" · Match over":""}`:rules.ballInHand?`BALL IN HAND${rules.house?.scratchKitchen?" · behind head string":""}`:rules.breakShot?"BREAK SHOT":safetyArmed?"SAFETY DECLARED":"At table";$("p1Score").classList.toggle("active",rules.current===0);$("p2Score").classList.toggle("active",rules.current===1);$("p1RackScore").textContent=rules.matchScore[0];$("p2RackScore").textContent=rules.matchScore[1];$("openTableState").textContent=rules.openTable?"OPEN":"CLOSED";$("p1Group").textContent=rules.players[0].group?rules.players[0].group.toUpperCase():"—";$("p2Group").textContent=rules.players[1].group?rules.players[1].group.toUpperCase():"—";$("p1Remaining").textContent=rules.players[0].group?`${rules.players[0].remaining} remaining`:"P1 group";$("p2Remaining").textContent=rules.players[1].group?`${rules.players[1].remaining} remaining`:"P2 group";$("ballInHandState").textContent=rules.ballInHand?"YES":"NO"}
function renderTimeline(){const x=$("timeline"),shots=events.filter(e=>e.type==="shot");$("shotCountLabel").textContent=`${shots.length} shots`;if(!events.length){x.className="empty";x.textContent="No events yet.";return}x.className="";x.innerHTML=events.slice().reverse().map(e=>`<div class="timeline-event"><span class="time">${fmt(e.t)}</span><div><b>${esc(e.type.replaceAll("-"," ").toUpperCase())}</b><small>${esc(e.note)}</small></div><span>${e.type==="highlight"?"★":e.type==="shot"?"●":e.type==="rack"?"🏆":"·"}</span></div>`).join("")}
function potRate(p){const s=rules?.players[p];if(!s)return 0;const attempts=s.pots+s.misses+s.scratches;return attempts?Math.round(s.pots/attempts*100):0}
function renderMetrics(){const p0=rules?.players[0],p1=rules?.players[1],items=[["Shots",(p0?.shots||0)+(p1?.shots||0)],["P1 pot %",potRate(0)+"%"],["P2 pot %",potRate(1)+"%"],["Scratches",(p0?.scratches||0)+(p1?.scratches||0)],["P1 long run",p0?.longestRun||0],["P2 long run",p1?.longestRun||0]];$("metrics").innerHTML=items.map(([a,b])=>`<div class="metric"><b>${b}</b><span>${a}</span></div>`).join("")}
function renderInsights(){if(!rules){$("insights").className="empty";$("insights").textContent="Play a few shots first.";return}const out=[];for(let i=0;i<2;i++){const p=rules.players[i];if(p.shots>=3){out.push(`<div class="insight"><b>${esc(name(i))}: ${potRate(i)}% tagged pot rate</b><span>${p.pots} pots · ${p.misses} misses · ${p.scratches} scratches · longest run ${p.longestRun}</span></div>`);if(p.scratches>=2)out.push(`<div class="insight"><b>${esc(name(i))}: cue-ball control warning</b><span>${p.scratches} scratches recorded.</span></div>`)}}$("insights").className=out.length?"":"empty";$("insights").innerHTML=out.join("")||"Play a few shots first."}
async function renderRecordings(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];const vids=(await dbAll("videos")).filter(v=>!sessionId||v.sessionId===sessionId).sort((a,b)=>a.index-b.index),x=$("recordings");if(!vids.length){x.className="empty";x.textContent="No video saved yet.";return}x.className="";x.innerHTML="";for(const v of vids){const u=URL.createObjectURL(v.blob);objectUrls.push(u);const ext=(v.type||"").includes("webm")?"webm":"mp4",d=document.createElement("div");d.className="recording";d.innerHTML=`<span>${fmt(v.start)}</span><div><b>Segment ${v.index+1}</b><small>${(v.blob.size/1048576).toFixed(1)} MB · ${fmt(v.end-v.start)}</small></div><a class="download" href="${u}" download="${v.id}.${ext}">Save</a>`;x.appendChild(d)}}
async function renderHistory(){const ss=(await dbAll("sessions")).sort((a,b)=>String(b.startedAt).localeCompare(String(a.startedAt))).slice(0,20),x=$("history");if(!ss.length){x.className="empty";x.textContent="No previous games.";return}x.className="";x.innerHTML=ss.map(s=>`<div class="history-row"><span>🎱</span><div><b>${esc(s.p1)} vs ${esc(s.p2)}</b><small>${esc(s.rulesetLabel)} · ${fmt(s.duration)} · ${s.events?.filter(e=>e.type==="shot").length||0} shots</small></div><span>${new Date(s.startedAt).toLocaleDateString()}</span></div>`).join("")}
function renderAll(){renderRules();renderTimeline();renderMetrics();renderInsights();renderRecordings();renderHistory()}
async function saveSession(ended){if(!sessionId)return;await dbPut("sessions",{id:sessionId,p1:name(0),p2:name(1),ruleset:$("ruleset").value,rulesetLabel:$("rulesLabel").textContent,startedAt:new Date(Date.now()-nowSec()*1000).toISOString(),endedAt:ended?new Date().toISOString():null,duration:nowSec(),calibration,events,rules:rules?.snapshot()})}
async function updateStorage(){if(navigator.storage?.estimate){const e=await navigator.storage.estimate();$("storageBadge").textContent=`Storage: ${(e.usage/1048576).toFixed(0)} MB / ${(e.quota/1073741824).toFixed(1)} GB`}}
$("exportBtn").onclick=async()=>{const ss=await dbAll("sessions"),s=ss.find(x=>x.id===sessionId)||ss[ss.length-1];if(!s)return alert("No saved session");const b=new Blob([JSON.stringify(s,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`${s.id}.json`;a.click()};
$("emailBtn").onclick=()=>{if(!rules)return alert("No game summary yet");const p0=rules.players[0],p1=rules.players[1],body=`PoolCam game summary\n\n${name(0)} ${rules.matchScore[0]} - ${rules.matchScore[1]} ${name(1)}\nDuration: ${fmt(nowSec())}\n\n${name(0)}: ${p0.shots} shots, ${p0.pots} pots, ${p0.misses} misses, ${p0.scratches} scratches, ${potRate(0)}% pot rate, longest run ${p0.longestRun}\n${name(1)}: ${p1.shots} shots, ${p1.pots} pots, ${p1.misses} misses, ${p1.scratches} scratches, ${potRate(1)}% pot rate, longest run ${p1.longestRun}`;location.href=`mailto:${encodeURIComponent($("reportEmail").value)}?subject=${encodeURIComponent("🎱 PoolCam Game Summary")}&body=${encodeURIComponent(body)}`};
$("clearDataBtn").onclick=async()=>{if(!confirm("Delete all PoolCam sessions and videos stored by this browser?"))return;await dbClear("sessions");await dbClear("videos");renderAll();updateStorage()};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});navigator.storage?.persist?.().catch(()=>{});renderAll();updateStorage();
